# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



# TestFlight
# development
platform :ios do
  desc "Upload a new development build to TestFlight"
  lane :testflightdev do
    increment_build_number(xcodeproj: "submanager.xcodeproj")
    build_app(workspace: "submanager.xcworkspace", scheme: "submanager Debug")
    upload_to_testflight
    skip_waiting_for_build_processing
  end
end

# production
platform :ios do
  desc "Upload a new production build to TestFlight"
  lane :testflightprod do
    increment_build_number(xcodeproj: "submanager.xcodeproj")
    build_app(workspace: "submanager.xcworkspace", scheme: "submanager Release")
    upload_to_testflight
    skip_waiting_for_build_processing
  end
end



# Firebase App Distribution
# development
platform :ios do
  desc "Upload a new development build to Firebase App Distribution"
  lane :firebasedev do
    increment_build_number(xcodeproj: "submanager.xcodeproj")
    build_app(workspace: "submanager.xcworkspace", scheme: "submanager Debug")
    firebase_app_distribution(
      groups: "engineering",
      release_notes: "Fastlane upload."
    )
  end
end

# production
platform :ios do
  desc "Upload a new production build to Firebase App Distribution"
  lane :firebaseprod do
    increment_build_number(xcodeproj: "submanager.xcodeproj")
    build_app(workspace: "submanager.xcworkspace", scheme: "submanager Release")
    firebase_app_distribution(
      groups: "engineering",
      release_notes: "Fastlane upload."
    )
  end
end
